# Generated by Django 5.2.7 on 2025-12-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Banho', 'Banho'), ('Tosa', 'Tosa'), ('Consulta', 'Consulta'), ('Vacinação', 'Vacinação'), ('Hospedagem', 'Hospedagem'), ('Outros', 'Outros')], default='Outros', max_length=20),
        ),
    ]
