# Generated by Django 5.2.7 on 2025-12-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
