# Generated by Django 5.2.7 on 2025-10-26 00:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_produto_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
